training_data = [
    {"text": 'Where is my order?', "intent": 'check_order_status' },
    {"text": 'What is the status of my order #12345?', "intent": 'check_order_status' },
    {"text": 'Track my order', "intent": 'check_order_status' },
    {"text": 'When will my package arrive?', "intent": 'check_order_status' },
    {"text": 'track order', "intent": 'check_order_status' },
    {"text": 'Where is my package?', "intent": 'check_order_status' },
    {"text": 'Can you check my order status?', "intent": 'check_order_status' },
    {"text": 'I want to track my order', "intent": 'check_order_status' },
    {"text": 'What happened to my order?', "intent": 'check_order_status' },
    {"text": 'Has my order shipped yet?', "intent": 'check_order_status' },
    {"text": 'Order status please', "intent": 'check_order_status' },
    {"text": 'Check my order', "intent": 'check_order_status' },
    {"text": 'Where is order 67890?', "intent": 'check_order_status' },
    {"text": 'tracking for order #54321', "intent": 'check_order_status' },
    {"text": 'When is my delivery coming?', "intent": 'check_order_status' },
    {"text": 'Is my package still in transit?', "intent": 'check_order_status' },
    {"text": 'Check delivery date for order #11111', "intent": 'check_order_status' },
    {"text": "Where's my order at?", "intent": 'check_order_status' },
    {"text": 'Can I get an update on order #22222?', "intent": 'check_order_status' },
    {"text": 'Status of my purchase?', "intent": 'check_order_status' },
    {"text": 'Did my order ship?', "intent": 'check_order_status' },
    {"text": 'Where did my package get to?', "intent": 'check_order_status' },
    {"text": 'Track delivery of order #99999', "intent": 'check_order_status' },
    {"text": 'I need tracking info for my order', "intent": 'check_order_status' },
    {"text": 'When will order #88888 be delivered?', "intent": 'check_order_status' },
    {"text": 'My package tracking number status', "intent": 'check_order_status' },
    {"text": 'Is my order on its way?', "intent": 'check_order_status' },
    {"text": 'Status check on order #77777', "intent": 'check_order_status' },
    {"text": "I haven't received my order yet", "intent": 'check_order_status' },
    {"text": 'How do I trace my order?', "intent": 'check_order_status' },
    {"text": 'Where is my shipment?', "intent": 'check_order_status' },
    {"text": 'Has order #66666 been dispatched?', "intent": 'check_order_status' },
    {"text": 'Expected delivery time for order', "intent": 'check_order_status' },
    {"text": 'Is my order still coming?', "intent": 'check_order_status' },
    {"text": 'Track parcel status', "intent": 'check_order_status' },
    {"text": 'My order has not arrived', "intent": 'check_order_status' },
    {"text": 'Where is the shipping tracking for #55555?', "intent": 'check_order_status' },
    {"text": 'Can you track my package please?', "intent": 'check_order_status' },
    {"text": 'Status of shipment', "intent": 'check_order_status' },
    {"text": 'Find my order status', "intent": 'check_order_status' },
    {"text": 'I want to cancel my order', "intent": 'cancel_order' },
    {"text": 'Please cancel order #67890', "intent": 'cancel_order' },
    {"text": 'Cancel my recent purchase', "intent": 'cancel_order' },
    {"text": 'Cancel order', "intent": 'cancel_order' },
    {"text": 'I want to cancel', "intent": 'cancel_order' },
    {"text": 'Stop my order', "intent": 'cancel_order' },
    {"text": 'Please stop my order', "intent": 'cancel_order' },
    {"text": 'I changed my mind, cancel my order', "intent": 'cancel_order' },
    {"text": 'Can you cancel my purchase?', "intent": 'cancel_order' },
    {"text": 'Cancel my order please', "intent": 'cancel_order' },
    {"text": "I don't want this order anymore", "intent": 'cancel_order' },
    {"text": 'Stop the shipment for order #33333', "intent": 'cancel_order' },
    {"text": 'Cancel order #44444', "intent": 'cancel_order' },
    {"text": 'I need to abort my order', "intent": 'cancel_order' },
    {"text": 'Can I void my order?', "intent": 'cancel_order' },
    {"text": 'Please terminate order #12121', "intent": 'cancel_order' },
    {"text": "Don't send my order", "intent": 'cancel_order' },
    {"text": 'I would like to cancel order #23232', "intent": 'cancel_order' },
    {"text": 'Stop processing my order', "intent": 'cancel_order' },
    {"text": 'Cancel my buy', "intent": 'cancel_order' },
    {"text": 'Void my recent transaction', "intent": 'cancel_order' },
    {"text": 'Can you delete my order?', "intent": 'cancel_order' },
    {"text": 'Kill order #34343', "intent": 'cancel_order' },
    {"text": 'I want to withdraw my order', "intent": 'cancel_order' },
    {"text": 'Please cancel my shipping', "intent": 'cancel_order' },
    {"text": 'Revoke my purchase #45454', "intent": 'cancel_order' },
    {"text": 'I changed my mind about this order', "intent": 'cancel_order' },
    {"text": 'Cancel the purchase please', "intent": 'cancel_order' },
    {"text": 'Stop order #56565 from shipping', "intent": 'cancel_order' },
    {"text": "Don't ship my items", "intent": 'cancel_order' },
    {"text": 'Cancel my order right away', "intent": 'cancel_order' },
    {"text": 'Delete order #78787', "intent": 'cancel_order' },
    {"text": 'I need to stop a pending purchase', "intent": 'cancel_order' },
    {"text": 'Abort shipment of order #98989', "intent": 'cancel_order' },
    {"text": 'I want to pull back my order', "intent": 'cancel_order' },
    {"text": 'I want a refund', "intent": 'request_refund' },
    {"text": 'How do I get my money back?', "intent": 'request_refund' },
    {"text": 'I need to return this item', "intent": 'request_refund' },
    {"text": 'Request refund', "intent": 'request_refund' },
    {"text": 'refund please', "intent": 'request_refund' },
    {"text": 'I need my money back', "intent": 'request_refund' },
    {"text": 'give me a refund', "intent": 'request_refund' },
    {"text": 'Can I get my money back?', "intent": 'request_refund' },
    {"text": 'I would like a refund', "intent": 'request_refund' },
    {"text": 'Process my refund', "intent": 'request_refund' },
    {"text": 'I want to return and get refund', "intent": 'request_refund' },
    {"text": 'Please refund my order', "intent": 'request_refund' },
    {"text": "I'd like to return order #11223 for a refund", "intent": 'request_refund' },
    {"text": 'Refund me for order #44556', "intent": 'request_refund' },
    {"text": 'Return process for purchase', "intent": 'request_refund' },
    {"text": 'I want a refund on order #77889', "intent": 'request_refund' },
    {"text": 'How to get a refund?', "intent": 'request_refund' },
    {"text": 'I need a reimbursement for this order', "intent": 'request_refund' },
    {"text": 'Can you refund my payment?', "intent": 'request_refund' },
    {"text": 'Refund request for order #99001', "intent": 'request_refund' },
    {"text": 'I want my cash back', "intent": 'request_refund' },
    {"text": 'Reimburse me please', "intent": 'request_refund' },
    {"text": 'Send back my payment for order #12131', "intent": 'request_refund' },
    {"text": 'I need to request a return', "intent": 'request_refund' },
    {"text": 'Return order #14151 for a full refund', "intent": 'request_refund' },
    {"text": 'Money back please', "intent": 'request_refund' },
    {"text": 'My item is defective, I want a refund', "intent": 'request_refund' },
    {"text": 'I need a refund on my purchase #16171', "intent": 'request_refund' },
    {"text": 'How do I return this product?', "intent": 'request_refund' },
    {"text": 'Initiate refund for order #18191', "intent": 'request_refund' },
    {"text": 'I want to get a refund for my order', "intent": 'request_refund' },
    {"text": 'Please return money for order #20212', "intent": 'request_refund' },
    {"text": 'Can I return this for cash?', "intent": 'request_refund' },
    {"text": 'Reimburse order #22232', "intent": 'request_refund' },
    {"text": 'I need to get my cash back for this', "intent": 'request_refund' },
    {"text": 'Hello', "intent": 'greeting' },
    {"text": 'Hi there', "intent": 'greeting' },
    {"text": 'Hey, I need help', "intent": 'greeting' },
    {"text": 'Hi', "intent": 'greeting' },
    {"text": 'Hey', "intent": 'greeting' },
    {"text": 'Good morning', "intent": 'greeting' },
    {"text": 'Good evening', "intent": 'greeting' },
    {"text": 'Hello, I need some help', "intent": 'greeting' },
    {"text": 'Hi, can you help me?', "intent": 'greeting' },
    {"text": 'Greetings', "intent": 'greeting' },
    {"text": 'Howdy!', "intent": 'greeting' },
    {"text": 'Yo!', "intent": 'greeting' },
    {"text": 'Hello bot', "intent": 'greeting' },
    {"text": 'Hey there', "intent": 'greeting' },
    {"text": 'Anyone available?', "intent": 'greeting' },
    {"text": 'Hi helper', "intent": 'greeting' },
    {"text": 'Good afternoon', "intent": 'greeting' },
    {"text": 'Hello support', "intent": 'greeting' },
    {"text": 'Hi assistant', "intent": 'greeting' },
    {"text": 'Hey buddy', "intent": 'greeting' },
    {"text": 'Hello there', "intent": 'greeting' },
    {"text": 'Are you online?', "intent": 'greeting' },
    {"text": 'Hi there support', "intent": 'greeting' },
    {"text": 'Good day', "intent": 'greeting' },
    {"text": 'Hello friend', "intent": 'greeting' },
    {"text": 'Hey helper!', "intent": 'greeting' },
    {"text": 'Hi there bot', "intent": 'greeting' },
    {"text": 'Are you there?', "intent": 'greeting' },
    {"text": 'Greetings team', "intent": 'greeting' },
    {"text": 'Hi, need support', "intent": 'greeting' },
    {"text": 'Bye', "intent": 'goodbye' },
    {"text": 'Thank you, goodbye', "intent": 'goodbye' },
    {"text": "That's all I needed", "intent": 'goodbye' },
    {"text": 'Goodbye', "intent": 'goodbye' },
    {"text": 'See you later', "intent": 'goodbye' },
    {"text": 'Thanks, bye', "intent": 'goodbye' },
    {"text": 'That will be all', "intent": 'goodbye' },
    {"text": 'Thank you for your help', "intent": 'goodbye' },
    {"text": "I'm done, thanks", "intent": 'goodbye' },
    {"text": 'Have a good day', "intent": 'goodbye' },
    {"text": 'Bye bye!', "intent": 'goodbye' },
    {"text": 'See ya', "intent": 'goodbye' },
    {"text": 'Thanks for the support, bye', "intent": 'goodbye' },
    {"text": 'Okay bye', "intent": 'goodbye' },
    {"text": 'I will go now', "intent": 'goodbye' },
    {"text": 'Talk to you later', "intent": 'goodbye' },
    {"text": 'Thanks a lot, goodbye', "intent": 'goodbye' },
    {"text": 'See you soon', "intent": 'goodbye' },
    {"text": 'All set, thanks, bye', "intent": 'goodbye' },
    {"text": 'Have a nice day', "intent": 'goodbye' },
    {"text": 'Have a great day', "intent": 'goodbye' },
    {"text": 'Bye friend', "intent": 'goodbye' },
    {"text": 'Thanks, I am logging off', "intent": 'goodbye' },
    {"text": 'No more questions, thanks', "intent": 'goodbye' },
    {"text": 'Goodbye support', "intent": 'goodbye' },
    {"text": 'Thanks for help, bye', "intent": 'goodbye' },
    {"text": 'Catch you later', "intent": 'goodbye' },
    {"text": 'Bye, have a good one', "intent": 'goodbye' },
    {"text": "I'm off, goodbye", "intent": 'goodbye' },
    {"text": 'Thanks again, bye', "intent": 'goodbye' },
]

# All possible intents
INTENTS = [
    'check_order_status',
    'cancel_order',
    'request_refund',
    'greeting',
    'goodbye',
]
