training_data = [
    {"text": 'Where is my order?', "intent": 'check_order_status' },
    {"text": 'What is the status of my order #12345?', "intent": 'check_order_status' },
    {"text": 'Track my order', "intent": 'check_order_status' },
    {"text": 'When will my package arrive?', "intent": 'check_order_status' },
    {"text": 'track order', "intent": 'check_order_status' },
    {"text": 'Where is my package?', "intent": 'check_order_status' },
    {"text": 'Can you check my order status?', "intent": 'check_order_status' },
    {"text": 'I want to track my order', "intent": 'check_order_status' },
    {"text": 'What happened to my order?', "intent": 'check_order_status' },
    {"text": 'Has my order shipped yet?', "intent": 'check_order_status' },
    {"text": 'Order status please', "intent": 'check_order_status' },
    {"text": 'Check my order', "intent": 'check_order_status' },
    {"text": 'Where is order 67890?', "intent": 'check_order_status' },
    {"text": 'tracking for order #54321', "intent": 'check_order_status' },
    {"text": 'When is my delivery coming?', "intent": 'check_order_status' },
    {"text": 'Is my package still in transit?', "intent": 'check_order_status' },
    {"text": 'Check delivery date for order #11111', "intent": 'check_order_status' },
    {"text": "Where's my order at?", "intent": 'check_order_status' },
    {"text": 'Can I get an update on order #22222?', "intent": 'check_order_status' },
    {"text": 'Status of my purchase?', "intent": 'check_order_status' },
    {"text": 'Did my order ship?', "intent": 'check_order_status' },
    {"text": 'Where did my package get to?', "intent": 'check_order_status' },
    {"text": 'Track delivery of order #99999', "intent": 'check_order_status' },
    {"text": 'I need tracking info for my order', "intent": 'check_order_status' },
    {"text": 'When will order #88888 be delivered?', "intent": 'check_order_status' },
    {"text": 'My package tracking number status', "intent": 'check_order_status' },
    {"text": 'Is my order on its way?', "intent": 'check_order_status' },
    {"text": 'Status check on order #77777', "intent": 'check_order_status' },
    {"text": "I haven't received my order yet", "intent": 'check_order_status' },
    {"text": 'How do I trace my order?', "intent": 'check_order_status' },
    {"text": 'Where is my shipment?', "intent": 'check_order_status' },
    {"text": 'Has order #66666 been dispatched?', "intent": 'check_order_status' },
    {"text": 'Expected delivery time for order', "intent": 'check_order_status' },
    {"text": 'Is my order still coming?', "intent": 'check_order_status' },
    {"text": 'Track parcel status', "intent": 'check_order_status' },
    {"text": 'My order has not arrived', "intent": 'check_order_status' },
    {"text": 'Where is the shipping tracking for #55555?', "intent": 'check_order_status' },
    {"text": 'Can you track my package please?', "intent": 'check_order_status' },
    {"text": 'Status of shipment', "intent": 'check_order_status' },
    {"text": 'Find my order status', "intent": 'check_order_status' },
    {"text": 'I want to cancel my order', "intent": 'cancel_order' },
    {"text": 'Please cancel order #67890', "intent": 'cancel_order' },
    {"text": 'Cancel my recent purchase', "intent": 'cancel_order' },
    {"text": 'Cancel order', "intent": 'cancel_order' },
    {"text": 'I want to cancel', "intent": 'cancel_order' },
    {"text": 'Stop my order', "intent": 'cancel_order' },
    {"text": 'Please stop my order', "intent": 'cancel_order' },
    {"text": 'I changed my mind, cancel my order', "intent": 'cancel_order' },
    {"text": 'Can you cancel my purchase?', "intent": 'cancel_order' },
    {"text": 'Cancel my order please', "intent": 'cancel_order' },
    {"text": "I don't want this order anymore", "intent": 'cancel_order' },
    {"text": 'Stop the shipment for order #33333', "intent": 'cancel_order' },
    {"text": 'Cancel order #44444', "intent": 'cancel_order' },
    {"text": 'I need to abort my order', "intent": 'cancel_order' },
    {"text": 'Can I void my order?', "intent": 'cancel_order' },
    {"text": 'Please terminate order #12121', "intent": 'cancel_order' },
    {"text": "Don't send my order", "intent": 'cancel_order' },
    {"text": 'I would like to cancel order #23232', "intent": 'cancel_order' },
    {"text": 'Stop processing my order', "intent": 'cancel_order' },
    {"text": 'Cancel my buy', "intent": 'cancel_order' },
    {"text": 'Void my recent transaction', "intent": 'cancel_order' },
    {"text": 'Can you delete my order?', "intent": 'cancel_order' },
    {"text": 'Kill order #34343', "intent": 'cancel_order' },
    {"text": 'I want to withdraw my order', "intent": 'cancel_order' },
    {"text": 'Please cancel my shipping', "intent": 'cancel_order' },
    {"text": 'Revoke my purchase #45454', "intent": 'cancel_order' },
    {"text": 'I changed my mind about this order', "intent": 'cancel_order' },
    {"text": 'Cancel the purchase please', "intent": 'cancel_order' },
    {"text": 'Stop order #56565 from shipping', "intent": 'cancel_order' },
    {"text": "Don't ship my items", "intent": 'cancel_order' },
    {"text": 'Cancel my order right away', "intent": 'cancel_order' },
    {"text": 'Delete order #78787', "intent": 'cancel_order' },
    {"text": 'I need to stop a pending purchase', "intent": 'cancel_order' },
    {"text": 'Abort shipment of order #98989', "intent": 'cancel_order' },
    {"text": 'I want to pull back my order', "intent": 'cancel_order' },
    {"text": 'I want a refund', "intent": 'request_refund' },
    {"text": 'How do I get my money back?', "intent": 'request_refund' },
    {"text": 'I need to return this item', "intent": 'request_refund' },
    {"text": 'Request refund', "intent": 'request_refund' },
    {"text": 'refund please', "intent": 'request_refund' },
    {"text": 'I need my money back', "intent": 'request_refund' },
    {"text": 'give me a refund', "intent": 'request_refund' },
    {"text": 'Can I get my money back?', "intent": 'request_refund' },
    {"text": 'I would like a refund', "intent": 'request_refund' },
    {"text": 'Process my refund', "intent": 'request_refund' },
    {"text": 'I want to return and get refund', "intent": 'request_refund' },
    {"text": 'Please refund my order', "intent": 'request_refund' },
    {"text": "I'd like to return order #11223 for a refund", "intent": 'request_refund' },
    {"text": 'Refund me for order #44556', "intent": 'request_refund' },
    {"text": 'Return process for purchase', "intent": 'request_refund' },
    {"text": 'I want a refund on order #77889', "intent": 'request_refund' },
    {"text": 'How to get a refund?', "intent": 'request_refund' },
    {"text": 'I need a reimbursement for this order', "intent": 'request_refund' },
    {"text": 'Can you refund my payment?', "intent": 'request_refund' },
    {"text": 'Refund request for order #99001', "intent": 'request_refund' },
    {"text": 'I want my cash back', "intent": 'request_refund' },
    {"text": 'Reimburse me please', "intent": 'request_refund' },
    {"text": 'Send back my payment for order #12131', "intent": 'request_refund' },
    {"text": 'I need to request a return', "intent": 'request_refund' },
    {"text": 'Return order #14151 for a full refund', "intent": 'request_refund' },
    {"text": 'Money back please', "intent": 'request_refund' },
    {"text": 'My item is defective, I want a refund', "intent": 'request_refund' },
    {"text": 'I need a refund on my purchase #16171', "intent": 'request_refund' },
    {"text": 'How do I return this product?', "intent": 'request_refund' },
    {"text": 'Initiate refund for order #18191', "intent": 'request_refund' },
    {"text": 'I want to get a refund for my order', "intent": 'request_refund' },
    {"text": 'Please return money for order #20212', "intent": 'request_refund' },
    {"text": 'Can I return this for cash?', "intent": 'request_refund' },
    {"text": 'Reimburse order #22232', "intent": 'request_refund' },
    {"text": 'I need to get my cash back for this', "intent": 'request_refund' },
    {"text": 'Hello', "intent": 'greeting' },
    {"text": 'Hi there', "intent": 'greeting' },
    {"text": 'Hey, I need help', "intent": 'greeting' },
    {"text": 'Hi', "intent": 'greeting' },
    {"text": 'Hey', "intent": 'greeting' },
    {"text": 'Good morning', "intent": 'greeting' },
    {"text": 'Good evening', "intent": 'greeting' },
    {"text": 'Hello, I need some help', "intent": 'greeting' },
    {"text": 'Hi, can you help me?', "intent": 'greeting' },
    {"text": 'Greetings', "intent": 'greeting' },
    {"text": 'Howdy!', "intent": 'greeting' },
    {"text": 'Yo!', "intent": 'greeting' },
    {"text": 'Hello bot', "intent": 'greeting' },
    {"text": 'Hey there', "intent": 'greeting' },
    {"text": 'Anyone available?', "intent": 'greeting' },
    {"text": 'Hi helper', "intent": 'greeting' },
    {"text": 'Good afternoon', "intent": 'greeting' },
    {"text": 'Hello support', "intent": 'greeting' },
    {"text": 'Hi assistant', "intent": 'greeting' },
    {"text": 'Hey buddy', "intent": 'greeting' },
    {"text": 'Hello there', "intent": 'greeting' },
    {"text": 'Are you online?', "intent": 'greeting' },
    {"text": 'Hi there support', "intent": 'greeting' },
    {"text": 'Good day', "intent": 'greeting' },
    {"text": 'Hello friend', "intent": 'greeting' },
    {"text": 'Hey helper!', "intent": 'greeting' },
    {"text": 'Hi there bot', "intent": 'greeting' },
    {"text": 'Are you there?', "intent": 'greeting' },
    {"text": 'Greetings team', "intent": 'greeting' },
    {"text": 'Hi, need support', "intent": 'greeting' },
    {"text": 'Bye', "intent": 'goodbye' },
    {"text": 'Thank you, goodbye', "intent": 'goodbye' },
    {"text": "That's all I needed", "intent": 'goodbye' },
    {"text": 'Goodbye', "intent": 'goodbye' },
    {"text": 'See you later', "intent": 'goodbye' },
    {"text": 'Thanks, bye', "intent": 'goodbye' },
    {"text": 'That will be all', "intent": 'goodbye' },
    {"text": 'Thank you for your help', "intent": 'goodbye' },
    {"text": "I'm done, thanks", "intent": 'goodbye' },
    {"text": 'Have a good day', "intent": 'goodbye' },
    {"text": 'Bye bye!', "intent": 'goodbye' },
    {"text": 'See ya', "intent": 'goodbye' },
    {"text": 'Thanks for the support, bye', "intent": 'goodbye' },
    {"text": 'Okay bye', "intent": 'goodbye' },
    {"text": 'I will go now', "intent": 'goodbye' },
    {"text": 'Talk to you later', "intent": 'goodbye' },
    {"text": 'Thanks a lot, goodbye', "intent": 'goodbye' },
    {"text": 'See you soon', "intent": 'goodbye' },
    {"text": 'All set, thanks, bye', "intent": 'goodbye' },
    {"text": 'Have a nice day', "intent": 'goodbye' },
    {"text": 'Have a great day', "intent": 'goodbye' },
    {"text": 'Bye friend', "intent": 'goodbye' },
    {"text": 'Thanks, I am logging off', "intent": 'goodbye' },
    {"text": 'No more questions, thanks', "intent": 'goodbye' },
    {"text": 'Goodbye support', "intent": 'goodbye' },
    {"text": 'Thanks for help, bye', "intent": 'goodbye' },
    {"text": 'Catch you later', "intent": 'goodbye' },
    {"text": 'Bye, have a good one', "intent": 'goodbye' },
    {"text": "I'm off, goodbye", "intent": 'goodbye' },
    {"text": 'Thanks again, bye', "intent": 'goodbye' },

    {"text": 'How long does shipping take?', "intent": 'shipping_info' },
    {"text": 'What shipping options do you offer?', "intent": 'shipping_info' },
    {"text": 'Is express shipping available?', "intent": 'shipping_info' },
    {"text": 'How much does shipping cost?', "intent": 'shipping_info' },
    {"text": 'Do you offer free shipping?', "intent": 'shipping_info' },
    {"text": 'What are the delivery options?', "intent": 'shipping_info' },
    {"text": 'Can I get overnight shipping?', "intent": 'shipping_info' },
    {"text": 'How fast is standard shipping?', "intent": 'shipping_info' },
    {"text": 'Do you ship internationally?', "intent": 'shipping_info' },
    {"text": 'What carriers do you use for shipping?', "intent": 'shipping_info' },
    {"text": 'Is two-day shipping an option?', "intent": 'shipping_info' },
    {"text": 'How much is expedited shipping?', "intent": 'shipping_info' },
    {"text": 'Do you deliver on weekends?', "intent": 'shipping_info' },
    {"text": 'What is the shipping fee?', "intent": 'shipping_info' },
    {"text": 'Can I pick up my order instead of shipping?', "intent": 'shipping_info' },
    {"text": 'Do you offer same-day delivery?', "intent": 'shipping_info' },
    {"text": 'How long for ground shipping?', "intent": 'shipping_info' },
    {"text": 'Shipping rates to my area?', "intent": 'shipping_info' },
    {"text": 'Is priority mail available?', "intent": 'shipping_info' },
    {"text": 'When will my shipment arrive if I order today?', "intent": 'shipping_info' },
    {"text": 'Do you ship to PO boxes?', "intent": 'shipping_info' },
    {"text": 'What is the cheapest shipping method?', "intent": 'shipping_info' },
    {"text": 'Can I change my shipping speed?', "intent": 'shipping_info' },
    {"text": 'How are shipping costs calculated?', "intent": 'shipping_info' },
    {"text": 'Is there a flat rate for shipping?', "intent": 'shipping_info' },
    {"text": 'Do you offer economy shipping?', "intent": 'shipping_info' },
    {"text": 'Tell me about your delivery methods', "intent": 'shipping_info' },
    {"text": 'How long does international delivery take?', "intent": 'shipping_info' },
    {"text": 'What is your fastest shipping option?', "intent": 'shipping_info' },
    {"text": 'Shipping information please', "intent": 'shipping_info' },

    {"text": "What's your return policy?", "intent": 'return_policy' },
    {"text": 'Can I return an opened item?', "intent": 'return_policy' },
    {"text": 'How do I start a return?', "intent": 'return_policy' },
    {"text": 'What is the return window?', "intent": 'return_policy' },
    {"text": 'How many days do I have to return?', "intent": 'return_policy' },
    {"text": 'Do you accept returns on sale items?', "intent": 'return_policy' },
    {"text": 'Can I exchange instead of return?', "intent": 'return_policy' },
    {"text": 'What condition does the item need to be in for return?', "intent": 'return_policy' },
    {"text": 'Is return shipping free?', "intent": 'return_policy' },
    {"text": 'Do I need the original packaging to return?', "intent": 'return_policy' },
    {"text": 'How long does a return take to process?', "intent": 'return_policy' },
    {"text": 'Can I return a gift?', "intent": 'return_policy' },
    {"text": 'What items are non-returnable?', "intent": 'return_policy' },
    {"text": 'Do you have a satisfaction guarantee?', "intent": 'return_policy' },
    {"text": 'Can I return without a receipt?', "intent": 'return_policy' },
    {"text": 'Tell me about your return process', "intent": 'return_policy' },
    {"text": 'Return policy details', "intent": 'return_policy' },
    {"text": 'Can I return an item bought online in store?', "intent": 'return_policy' },
    {"text": 'Do I pay for return shipping?', "intent": 'return_policy' },
    {"text": 'How do I get a return label?', "intent": 'return_policy' },
    {"text": 'What is the deadline for returns?', "intent": 'return_policy' },
    {"text": 'Can I return after 30 days?', "intent": 'return_policy' },
    {"text": 'Are electronics returnable?', "intent": 'return_policy' },
    {"text": 'Return and exchange policy please', "intent": 'return_policy' },
    {"text": 'Do you offer free returns?', "intent": 'return_policy' },
    {"text": 'Where do I ship my return?', "intent": 'return_policy' },
    {"text": 'I want to know your return rules', "intent": 'return_policy' },
    {"text": 'Can I return a customized item?', "intent": 'return_policy' },
    {"text": 'Is there a restocking fee for returns?', "intent": 'return_policy' },
    {"text": 'How do returns work here?', "intent": 'return_policy' },

    {"text": 'Do you have this in blue?', "intent": 'product_inquiry' },
    {"text": 'Is this product in stock?', "intent": 'product_inquiry' },
    {"text": 'What sizes are available?', "intent": 'product_inquiry' },
    {"text": 'Can you tell me more about this product?', "intent": 'product_inquiry' },
    {"text": 'What materials is this made of?', "intent": 'product_inquiry' },
    {"text": 'Do you have this in a larger size?', "intent": 'product_inquiry' },
    {"text": 'Is this item available in other colors?', "intent": 'product_inquiry' },
    {"text": 'When will this be back in stock?', "intent": 'product_inquiry' },
    {"text": 'What are the dimensions of this product?', "intent": 'product_inquiry' },
    {"text": 'Does this come with a warranty?', "intent": 'product_inquiry' },
    {"text": 'Can I see product reviews?', "intent": 'product_inquiry' },
    {"text": 'What is the weight of this item?', "intent": 'product_inquiry' },
    {"text": 'Do you carry this brand?', "intent": 'product_inquiry' },
    {"text": 'Is this product on backorder?', "intent": 'product_inquiry' },
    {"text": 'How do I find the right size?', "intent": 'product_inquiry' },
    {"text": 'Product availability question', "intent": 'product_inquiry' },
    {"text": 'Do you have a size chart?', "intent": 'product_inquiry' },
    {"text": 'What colors does this come in?', "intent": 'product_inquiry' },
    {"text": 'Can I pre-order this item?', "intent": 'product_inquiry' },
    {"text": 'Tell me about the features of this product', "intent": 'product_inquiry' },
    {"text": 'Is this compatible with my device?', "intent": 'product_inquiry' },
    {"text": 'How long does the battery last?', "intent": 'product_inquiry' },
    {"text": 'What is the difference between these two models?', "intent": 'product_inquiry' },
    {"text": 'Do you sell accessories for this?', "intent": 'product_inquiry' },
    {"text": 'Is this available for store pickup?', "intent": 'product_inquiry' },
    {"text": 'Can you recommend a similar product?', "intent": 'product_inquiry' },
    {"text": 'Are there any alternatives to this item?', "intent": 'product_inquiry' },
    {"text": 'What are the specs of this product?', "intent": 'product_inquiry' },
    {"text": 'Do you have any new arrivals?', "intent": 'product_inquiry' },
    {"text": 'Is this item discontinued?', "intent": 'product_inquiry' },

    {"text": 'My payment was declined', "intent": 'payment_issue' },
    {"text": 'Which payment methods do you accept?', "intent": 'payment_issue' },
    {"text": 'I was charged twice', "intent": 'payment_issue' },
    {"text": 'My credit card is not going through', "intent": 'payment_issue' },
    {"text": 'Can I pay with PayPal?', "intent": 'payment_issue' },
    {"text": 'There is an error with my payment', "intent": 'payment_issue' },
    {"text": 'I see a pending charge on my card', "intent": 'payment_issue' },
    {"text": 'Do you accept Apple Pay?', "intent": 'payment_issue' },
    {"text": 'My transaction failed', "intent": 'payment_issue' },
    {"text": 'I was overcharged for my order', "intent": 'payment_issue' },
    {"text": 'Can I split my payment between two cards?', "intent": 'payment_issue' },
    {"text": 'Payment is not processing', "intent": 'payment_issue' },
    {"text": 'Do you accept debit cards?', "intent": 'payment_issue' },
    {"text": 'My billing address is wrong', "intent": 'payment_issue' },
    {"text": 'How do I update my payment method?', "intent": 'payment_issue' },
    {"text": 'I got charged but order did not go through', "intent": 'payment_issue' },
    {"text": 'Can I pay with a gift card?', "intent": 'payment_issue' },
    {"text": 'Why was my payment rejected?', "intent": 'payment_issue' },
    {"text": 'I need to change my billing information', "intent": 'payment_issue' },
    {"text": 'Do you offer installment payments?', "intent": 'payment_issue' },
    {"text": 'Is there a payment plan available?', "intent": 'payment_issue' },
    {"text": 'My coupon did not reduce the total', "intent": 'payment_issue' },
    {"text": 'Checkout keeps giving me an error', "intent": 'payment_issue' },
    {"text": 'Can I pay by bank transfer?', "intent": 'payment_issue' },
    {"text": 'The total amount seems wrong', "intent": 'payment_issue' },
    {"text": 'I want to dispute a charge', "intent": 'payment_issue' },
    {"text": 'Do you accept cryptocurrency?', "intent": 'payment_issue' },
    {"text": 'How do I add a new credit card?', "intent": 'payment_issue' },
    {"text": 'My promo code is not applying at checkout', "intent": 'payment_issue' },
    {"text": 'Payment method question', "intent": 'payment_issue' },

    {"text": 'I forgot my password', "intent": 'account_help' },
    {"text": 'How do I change my email?', "intent": 'account_help' },
    {"text": "I can't log into my account", "intent": 'account_help' },
    {"text": 'How do I reset my password?', "intent": 'account_help' },
    {"text": 'I need to update my profile', "intent": 'account_help' },
    {"text": 'How do I create an account?', "intent": 'account_help' },
    {"text": 'My account is locked', "intent": 'account_help' },
    {"text": 'I want to delete my account', "intent": 'account_help' },
    {"text": 'How do I change my username?', "intent": 'account_help' },
    {"text": "I'm not receiving the verification email", "intent": 'account_help' },
    {"text": 'How do I update my address?', "intent": 'account_help' },
    {"text": 'I forgot my login email', "intent": 'account_help' },
    {"text": 'Can I merge two accounts?', "intent": 'account_help' },
    {"text": 'How do I enable two-factor authentication?', "intent": 'account_help' },
    {"text": 'My account was compromised', "intent": 'account_help' },
    {"text": 'I need help with my login', "intent": 'account_help' },
    {"text": 'How do I change my phone number on my account?', "intent": 'account_help' },
    {"text": 'Password reset is not working', "intent": 'account_help' },
    {"text": 'How do I sign up for an account?', "intent": 'account_help' },
    {"text": 'I want to change my account settings', "intent": 'account_help' },
    {"text": 'Can I change my registered email address?', "intent": 'account_help' },
    {"text": 'My login keeps failing', "intent": 'account_help' },
    {"text": 'How do I deactivate my account?', "intent": 'account_help' },
    {"text": 'I need to verify my email', "intent": 'account_help' },
    {"text": 'Account security question', "intent": 'account_help' },
    {"text": 'How do I log out of all devices?', "intent": 'account_help' },
    {"text": 'I want to update my personal information', "intent": 'account_help' },
    {"text": "I can't access my account", "intent": 'account_help' },
    {"text": 'Help me recover my account', "intent": 'account_help' },
    {"text": 'How do I manage my saved addresses?', "intent": 'account_help' },

    {"text": 'I want to speak to a manager', "intent": 'complaint' },
    {"text": 'This is unacceptable', "intent": 'complaint' },
    {"text": "I've been waiting too long", "intent": 'complaint' },
    {"text": 'I am very unhappy with your service', "intent": 'complaint' },
    {"text": 'This is the worst experience ever', "intent": 'complaint' },
    {"text": 'I want to file a complaint', "intent": 'complaint' },
    {"text": 'Your service is terrible', "intent": 'complaint' },
    {"text": 'I demand to speak with a supervisor', "intent": 'complaint' },
    {"text": 'This is not what I ordered', "intent": 'complaint' },
    {"text": 'I am extremely dissatisfied', "intent": 'complaint' },
    {"text": 'Nobody is helping me', "intent": 'complaint' },
    {"text": 'I have been on hold forever', "intent": 'complaint' },
    {"text": 'Your company has the worst support', "intent": 'complaint' },
    {"text": 'I want to escalate this issue', "intent": 'complaint' },
    {"text": 'This needs to be resolved immediately', "intent": 'complaint' },
    {"text": 'I am going to leave a bad review', "intent": 'complaint' },
    {"text": 'I am not satisfied with this response', "intent": 'complaint' },
    {"text": 'Get me someone who can actually help', "intent": 'complaint' },
    {"text": 'This is ridiculous', "intent": 'complaint' },
    {"text": 'I keep getting the runaround', "intent": 'complaint' },
    {"text": 'Your product quality is awful', "intent": 'complaint' },
    {"text": 'I have had it with your company', "intent": 'complaint' },
    {"text": 'Let me talk to a real person', "intent": 'complaint' },
    {"text": 'I want to make a formal complaint', "intent": 'complaint' },
    {"text": 'How do I report a problem?', "intent": 'complaint' },
    {"text": 'This is the third time I am calling about this', "intent": 'complaint' },
    {"text": 'I am very frustrated with this situation', "intent": 'complaint' },
    {"text": 'Nothing has been resolved', "intent": 'complaint' },
    {"text": 'Escalate my case to management', "intent": 'complaint' },
    {"text": 'I need to speak with someone in charge', "intent": 'complaint' },

    {"text": 'Thanks for your help', "intent": 'thank_you' },
    {"text": 'That was very helpful', "intent": 'thank_you' },
    {"text": 'I appreciate it', "intent": 'thank_you' },
    {"text": 'Thank you so much', "intent": 'thank_you' },
    {"text": 'You have been great', "intent": 'thank_you' },
    {"text": 'Thanks a lot', "intent": 'thank_you' },
    {"text": 'That really helped', "intent": 'thank_you' },
    {"text": 'I appreciate your assistance', "intent": 'thank_you' },
    {"text": 'Thank you for the quick response', "intent": 'thank_you' },
    {"text": 'You are awesome', "intent": 'thank_you' },
    {"text": 'Great job helping me', "intent": 'thank_you' },
    {"text": 'Thanks for resolving my issue', "intent": 'thank_you' },
    {"text": 'That solved my problem', "intent": 'thank_you' },
    {"text": 'Wonderful help, thank you', "intent": 'thank_you' },
    {"text": 'I really appreciate your time', "intent": 'thank_you' },
    {"text": 'Thanks for everything', "intent": 'thank_you' },
    {"text": 'You were very helpful', "intent": 'thank_you' },
    {"text": 'Perfect, thanks', "intent": 'thank_you' },
    {"text": 'Thanks for the information', "intent": 'thank_you' },
    {"text": 'Excellent support, thank you', "intent": 'thank_you' },
    {"text": 'Many thanks', "intent": 'thank_you' },
    {"text": 'I am grateful for your help', "intent": 'thank_you' },
    {"text": 'Thank you for being so patient', "intent": 'thank_you' },
    {"text": 'You made this so easy', "intent": 'thank_you' },
    {"text": 'Thanks for taking care of this', "intent": 'thank_you' },
    {"text": 'Really appreciate the support', "intent": 'thank_you' },
    {"text": 'Thank you for your patience', "intent": 'thank_you' },
    {"text": 'That was exactly what I needed', "intent": 'thank_you' },
    {"text": 'Cheers, thanks for the help', "intent": 'thank_you' },
    {"text": 'Much appreciated', "intent": 'thank_you' },

    {"text": 'What are your business hours?', "intent": 'faq_general' },
    {"text": 'How can I contact support?', "intent": 'faq_general' },
    {"text": 'Where are you located?', "intent": 'faq_general' },
    {"text": 'What is your phone number?', "intent": 'faq_general' },
    {"text": 'Do you have a physical store?', "intent": 'faq_general' },
    {"text": 'What are your hours of operation?', "intent": 'faq_general' },
    {"text": 'How do I reach customer service?', "intent": 'faq_general' },
    {"text": 'Is there an email I can write to?', "intent": 'faq_general' },
    {"text": 'Where is your headquarters?', "intent": 'faq_general' },
    {"text": 'Do you have a help center?', "intent": 'faq_general' },
    {"text": 'What days are you open?', "intent": 'faq_general' },
    {"text": 'Can I visit your office?', "intent": 'faq_general' },
    {"text": 'How do I contact you by phone?', "intent": 'faq_general' },
    {"text": 'Do you have live chat support?', "intent": 'faq_general' },
    {"text": 'What is your customer service email?', "intent": 'faq_general' },
    {"text": 'Are you open on holidays?', "intent": 'faq_general' },
    {"text": 'Tell me about your company', "intent": 'faq_general' },
    {"text": 'How long have you been in business?', "intent": 'faq_general' },
    {"text": 'What services do you provide?', "intent": 'faq_general' },
    {"text": 'Where can I find your FAQ?', "intent": 'faq_general' },
    {"text": 'Do you have a contact form?', "intent": 'faq_general' },
    {"text": 'When does customer service close?', "intent": 'faq_general' },
    {"text": 'Can I schedule a call with support?', "intent": 'faq_general' },
    {"text": 'What time zone are your hours in?', "intent": 'faq_general' },
    {"text": 'Is your support available 24/7?', "intent": 'faq_general' },
    {"text": 'Who should I contact for help?', "intent": 'faq_general' },
    {"text": 'Do you have social media accounts?', "intent": 'faq_general' },
    {"text": 'Where can I find your terms of service?', "intent": 'faq_general' },
    {"text": 'What is your privacy policy?', "intent": 'faq_general' },
    {"text": 'General information about your business', "intent": 'faq_general' },

    {"text": 'Can I change my shipping address?', "intent": 'change_order' },
    {"text": 'I want to add an item to my order', "intent": 'change_order' },
    {"text": 'Can I change the size?', "intent": 'change_order' },
    {"text": 'I need to modify my order', "intent": 'change_order' },
    {"text": 'Can I update the quantity on my order?', "intent": 'change_order' },
    {"text": 'I want to change the color of my item', "intent": 'change_order' },
    {"text": 'Can I swap an item in my order?', "intent": 'change_order' },
    {"text": 'I need to remove an item from my order', "intent": 'change_order' },
    {"text": 'Can I change my delivery date?', "intent": 'change_order' },
    {"text": 'I want to upgrade my shipping method', "intent": 'change_order' },
    {"text": 'Modify my existing order please', "intent": 'change_order' },
    {"text": 'Can I edit my order after placing it?', "intent": 'change_order' },
    {"text": 'I need to change the delivery address', "intent": 'change_order' },
    {"text": 'Add a gift note to my order', "intent": 'change_order' },
    {"text": 'Can I change my order before it ships?', "intent": 'change_order' },
    {"text": 'I want to update my shipping preferences', "intent": 'change_order' },
    {"text": 'Can I add gift wrapping to my order?', "intent": 'change_order' },
    {"text": 'Change the payment method on my order', "intent": 'change_order' },
    {"text": 'I placed the wrong order, can I fix it?', "intent": 'change_order' },
    {"text": 'How do I modify a placed order?', "intent": 'change_order' },
    {"text": 'I want to switch to a different product', "intent": 'change_order' },
    {"text": 'Update my order details', "intent": 'change_order' },
    {"text": 'Can I change the quantity of items?', "intent": 'change_order' },
    {"text": 'I want to adjust my order', "intent": 'change_order' },
    {"text": 'Can I combine two orders?', "intent": 'change_order' },
    {"text": 'Change my order to a different variant', "intent": 'change_order' },
    {"text": 'I need to correct my shipping info', "intent": 'change_order' },
    {"text": 'Update the billing address on my order', "intent": 'change_order' },
    {"text": 'Can I make changes to an existing order?', "intent": 'change_order' },
    {"text": 'I want to amend my purchase', "intent": 'change_order' },

    {"text": 'Do you have any promo codes?', "intent": 'promotion' },
    {"text": 'Are there any sales right now?', "intent": 'promotion' },
    {"text": 'How do I apply a coupon?', "intent": 'promotion' },
    {"text": 'Do you have any discounts available?', "intent": 'promotion' },
    {"text": 'Is there a first-time buyer discount?', "intent": 'promotion' },
    {"text": 'Any ongoing promotions?', "intent": 'promotion' },
    {"text": 'Where can I find coupon codes?', "intent": 'promotion' },
    {"text": 'Do you have a student discount?', "intent": 'promotion' },
    {"text": 'When is your next sale?', "intent": 'promotion' },
    {"text": 'How do I use a discount code?', "intent": 'promotion' },
    {"text": 'Are there any Black Friday deals?', "intent": 'promotion' },
    {"text": 'Can I stack multiple coupons?', "intent": 'promotion' },
    {"text": 'Do you have a loyalty program?', "intent": 'promotion' },
    {"text": 'Any special offers right now?', "intent": 'promotion' },
    {"text": 'Is there a referral discount?', "intent": 'promotion' },
    {"text": 'How do I get a promo code?', "intent": 'promotion' },
    {"text": 'Do you offer military discounts?', "intent": 'promotion' },
    {"text": 'Any deals for new customers?', "intent": 'promotion' },
    {"text": 'Where do I enter my coupon code?', "intent": 'promotion' },
    {"text": 'Do you have seasonal promotions?', "intent": 'promotion' },
    {"text": 'Can I get a bulk order discount?', "intent": 'promotion' },
    {"text": 'Are there any clearance items?', "intent": 'promotion' },
    {"text": 'Do you price match competitors?', "intent": 'promotion' },
    {"text": 'Is there a newsletter signup discount?', "intent": 'promotion' },
    {"text": 'What promotions are currently active?', "intent": 'promotion' },
    {"text": 'How do I redeem reward points?', "intent": 'promotion' },
    {"text": 'Do you have a rewards program?', "intent": 'promotion' },
    {"text": 'Any upcoming sales events?', "intent": 'promotion' },
    {"text": 'Can I get a discount on this order?', "intent": 'promotion' },
    {"text": 'Tell me about your current deals', "intent": 'promotion' },
]

# All possible intents
INTENTS = [
    'check_order_status',
    'cancel_order',
    'request_refund',
    'greeting',
    'goodbye',
    'shipping_info',
    'return_policy',
    'product_inquiry',
    'payment_issue',
    'account_help',
    'complaint',
    'thank_you',
    'faq_general',
    'change_order',
    'promotion',
]
