training_data = [
    # Check order status (40 examples)
    {"text": "Where is my order?", "intent": "check_order_status", "entities": {}},
    {"text": "What is the status of my order #12345?", "intent": "check_order_status", "entities": {"order_id": "12345"}},
    {"text": "Track my order", "intent": "check_order_status", "entities": {}},
    {"text": "When will my package arrive?", "intent": "check_order_status", "entities": {}},
    {"text": "track order", "intent": "check_order_status", "entities": {}},
    {"text": "Where is my package?", "intent": "check_order_status", "entities": {}},
    {"text": "Can you check my order status?", "intent": "check_order_status", "entities": {}},
    {"text": "I want to track my order", "intent": "check_order_status", "entities": {}},
    {"text": "What happened to my order?", "intent": "check_order_status", "entities": {}},
    {"text": "Has my order shipped yet?", "intent": "check_order_status", "entities": {}},
    {"text": "Order status please", "intent": "check_order_status", "entities": {}},
    {"text": "Check my order", "intent": "check_order_status", "entities": {}},
    {"text": "Where is order 67890?", "intent": "check_order_status", "entities": {"order_id": "67890"}},
    {"text": "tracking for order #54321", "intent": "check_order_status", "entities": {"order_id": "54321"}},
    {"text": "When is my delivery coming?", "intent": "check_order_status", "entities": {}},
    {"text": "Is my package still in transit?", "intent": "check_order_status", "entities": {}},
    {"text": "Check delivery date for order #11111", "intent": "check_order_status", "entities": {"order_id": "11111"}},
    {"text": "Where's my order at?", "intent": "check_order_status", "entities": {}},
    {"text": "Can I get an update on order #22222?", "intent": "check_order_status", "entities": {"order_id": "22222"}},
    {"text": "Status of my purchase?", "intent": "check_order_status", "entities": {}},
    {"text": "Did my order ship?", "intent": "check_order_status", "entities": {}},
    {"text": "Where did my package get to?", "intent": "check_order_status", "entities": {}},
    {"text": "Track delivery of order #99999", "intent": "check_order_status", "entities": {"order_id": "99999"}},
    {"text": "I need tracking info for my order", "intent": "check_order_status", "entities": {}},
    {"text": "When will order #88888 be delivered?", "intent": "check_order_status", "entities": {"order_id": "88888"}},
    {"text": "My package tracking number status", "intent": "check_order_status", "entities": {}},
    {"text": "Is my order on its way?", "intent": "check_order_status", "entities": {}},
    {"text": "Status check on order #77777", "intent": "check_order_status", "entities": {"order_id": "77777"}},
    {"text": "I haven't received my order yet", "intent": "check_order_status", "entities": {}},
    {"text": "How do I trace my order?", "intent": "check_order_status", "entities": {}},
    {"text": "Where is my shipment?", "intent": "check_order_status", "entities": {}},
    {"text": "Has order #66666 been dispatched?", "intent": "check_order_status", "entities": {"order_id": "66666"}},
    {"text": "Expected delivery time for order", "intent": "check_order_status", "entities": {}},
    {"text": "Is my order still coming?", "intent": "check_order_status", "entities": {}},
    {"text": "Track parcel status", "intent": "check_order_status", "entities": {}},
    {"text": "My order has not arrived", "intent": "check_order_status", "entities": {}},
    {"text": "Where is the shipping tracking for #55555?", "intent": "check_order_status", "entities": {"order_id": "55555"}},
    {"text": "Can you track my package please?", "intent": "check_order_status", "entities": {}},
    {"text": "Status of shipment", "intent": "check_order_status", "entities": {}},
    {"text": "Find my order status", "intent": "check_order_status", "entities": {}},

    # Cancel order (35 examples)
    {"text": "I want to cancel my order", "intent": "cancel_order", "entities": {}},
    {"text": "Please cancel order #67890", "intent": "cancel_order", "entities": {"order_id": "67890"}},
    {"text": "Cancel my recent purchase", "intent": "cancel_order", "entities": {}},
    {"text": "Cancel order", "intent": "cancel_order", "entities": {}},
    {"text": "I want to cancel", "intent": "cancel_order", "entities": {}},
    {"text": "Stop my order", "intent": "cancel_order", "entities": {}},
    {"text": "Please stop my order", "intent": "cancel_order", "entities": {}},
    {"text": "I changed my mind, cancel my order", "intent": "cancel_order", "entities": {}},
    {"text": "Can you cancel my purchase?", "intent": "cancel_order", "entities": {}},
    {"text": "Cancel my order please", "intent": "cancel_order", "entities": {}},
    {"text": "I don't want this order anymore", "intent": "cancel_order", "entities": {}},
    {"text": "Stop the shipment for order #33333", "intent": "cancel_order", "entities": {"order_id": "33333"}},
    {"text": "Cancel order #44444", "intent": "cancel_order", "entities": {"order_id": "44444"}},
    {"text": "I need to abort my order", "intent": "cancel_order", "entities": {}},
    {"text": "Can I void my order?", "intent": "cancel_order", "entities": {}},
    {"text": "Please terminate order #12121", "intent": "cancel_order", "entities": {"order_id": "12121"}},
    {"text": "Don't send my order", "intent": "cancel_order", "entities": {}},
    {"text": "I would like to cancel order #23232", "intent": "cancel_order", "entities": {"order_id": "23232"}},
    {"text": "Stop processing my order", "intent": "cancel_order", "entities": {}},
    {"text": "Cancel my buy", "intent": "cancel_order", "entities": {}},
    {"text": "Void my recent transaction", "intent": "cancel_order", "entities": {}},
    {"text": "Can you delete my order?", "intent": "cancel_order", "entities": {}},
    {"text": "Kill order #34343", "intent": "cancel_order", "entities": {"order_id": "34343"}},
    {"text": "I want to withdraw my order", "intent": "cancel_order", "entities": {}},
    {"text": "Please cancel my shipping", "intent": "cancel_order", "entities": {}},
    {"text": "Revoke my purchase #45454", "intent": "cancel_order", "entities": {"order_id": "45454"}},
    {"text": "I changed my mind about this order", "intent": "cancel_order", "entities": {}},
    {"text": "Cancel the purchase please", "intent": "cancel_order", "entities": {}},
    {"text": "Stop order #56565 from shipping", "intent": "cancel_order", "entities": {"order_id": "56565"}},
    {"text": "Don't ship my items", "intent": "cancel_order", "entities": {}},
    {"text": "Cancel my order right away", "intent": "cancel_order", "entities": {}},
    {"text": "Delete order #78787", "intent": "cancel_order", "entities": {"order_id": "78787"}},
    {"text": "I need to stop a pending purchase", "intent": "cancel_order", "entities": {}},
    {"text": "Abort shipment of order #98989", "intent": "cancel_order", "entities": {"order_id": "98989"}},
    {"text": "I want to pull back my order", "intent": "cancel_order", "entities": {}},

    # Request refund (35 examples)
    {"text": "I want a refund", "intent": "request_refund", "entities": {}},
    {"text": "How do I get my money back?", "intent": "request_refund", "entities": {}},
    {"text": "I need to return this item", "intent": "request_refund", "entities": {}},
    {"text": "Request refund", "intent": "request_refund", "entities": {}},
    {"text": "refund please", "intent": "request_refund", "entities": {}},
    {"text": "I need my money back", "intent": "request_refund", "entities": {}},
    {"text": "give me a refund", "intent": "request_refund", "entities": {}},
    {"text": "Can I get my money back?", "intent": "request_refund", "entities": {}},
    {"text": "I would like a refund", "intent": "request_refund", "entities": {}},
    {"text": "Process my refund", "intent": "request_refund", "entities": {}},
    {"text": "I want to return and get refund", "intent": "request_refund", "entities": {}},
    {"text": "Please refund my order", "intent": "request_refund", "entities": {}},
    {"text": "I'd like to return order #11223 for a refund", "intent": "request_refund", "entities": {"order_id": "11223"}},
    {"text": "Refund me for order #44556", "intent": "request_refund", "entities": {"order_id": "44556"}},
    {"text": "Return process for purchase", "intent": "request_refund", "entities": {}},
    {"text": "I want a refund on order #77889", "intent": "request_refund", "entities": {"order_id": "77889"}},
    {"text": "How to get a refund?", "intent": "request_refund", "entities": {}},
    {"text": "I need a reimbursement for this order", "intent": "request_refund", "entities": {}},
    {"text": "Can you refund my payment?", "intent": "request_refund", "entities": {}},
    {"text": "Refund request for order #99001", "intent": "request_refund", "entities": {"order_id": "99001"}},
    {"text": "I want my cash back", "intent": "request_refund", "entities": {}},
    {"text": "Reimburse me please", "intent": "request_refund", "entities": {}},
    {"text": "Send back my payment for order #12131", "intent": "request_refund", "entities": {"order_id": "12131"}},
    {"text": "I need to request a return", "intent": "request_refund", "entities": {}},
    {"text": "Return order #14151 for a full refund", "intent": "request_refund", "entities": {"order_id": "14151"}},
    {"text": "Money back please", "intent": "request_refund", "entities": {}},
    {"text": "My item is defective, I want a refund", "intent": "request_refund", "entities": {}},
    {"text": "I need a refund on my purchase #16171", "intent": "request_refund", "entities": {"order_id": "16171"}},
    {"text": "How do I return this product?", "intent": "request_refund", "entities": {}},
    {"text": "Initiate refund for order #18191", "intent": "request_refund", "entities": {"order_id": "18191"}},
    {"text": "I want to get a refund for my order", "intent": "request_refund", "entities": {}},
    {"text": "Please return money for order #20212", "intent": "request_refund", "entities": {"order_id": "20212"}},
    {"text": "Can I return this for cash?", "intent": "request_refund", "entities": {}},
    {"text": "Reimburse order #22232", "intent": "request_refund", "entities": {"order_id": "22232"}},
    {"text": "I need to get my cash back for this", "intent": "request_refund", "entities": {}},

    # Greeting (30 examples)
    {"text": "Hello", "intent": "greeting", "entities": {}},
    {"text": "Hi there", "intent": "greeting", "entities": {}},
    {"text": "Hey, I need help", "intent": "greeting", "entities": {}},
    {"text": "Hi", "intent": "greeting", "entities": {}},
    {"text": "Hey", "intent": "greeting", "entities": {}},
    {"text": "Good morning", "intent": "greeting", "entities": {}},
    {"text": "Good evening", "intent": "greeting", "entities": {}},
    {"text": "Hello, I need some help", "intent": "greeting", "entities": {}},
    {"text": "Hi, can you help me?", "intent": "greeting", "entities": {}},
    {"text": "Greetings", "intent": "greeting", "entities": {}},
    {"text": "Howdy!", "intent": "greeting", "entities": {}},
    {"text": "Yo!", "intent": "greeting", "entities": {}},
    {"text": "Hello bot", "intent": "greeting", "entities": {}},
    {"text": "Hey there", "intent": "greeting", "entities": {}},
    {"text": "Anyone available?", "intent": "greeting", "entities": {}},
    {"text": "Hi helper", "intent": "greeting", "entities": {}},
    {"text": "Good afternoon", "intent": "greeting", "entities": {}},
    {"text": "Hello support", "intent": "greeting", "entities": {}},
    {"text": "Hi assistant", "intent": "greeting", "entities": {}},
    {"text": "Hey buddy", "intent": "greeting", "entities": {}},
    {"text": "Hello there", "intent": "greeting", "entities": {}},
    {"text": "Are you online?", "intent": "greeting", "entities": {}},
    {"text": "Hi there support", "intent": "greeting", "entities": {}},
    {"text": "Good day", "intent": "greeting", "entities": {}},
    {"text": "Hello friend", "intent": "greeting", "entities": {}},
    {"text": "Hey helper!", "intent": "greeting", "entities": {}},
    {"text": "Hi there bot", "intent": "greeting", "entities": {}},
    {"text": "Are you there?", "intent": "greeting", "entities": {}},
    {"text": "Greetings team", "intent": "greeting", "entities": {}},
    {"text": "Hi, need support", "intent": "greeting", "entities": {}},

    # Goodbye (30 examples)
    {"text": "Bye", "intent": "goodbye", "entities": {}},
    {"text": "Thank you, goodbye", "intent": "goodbye", "entities": {}},
    {"text": "That's all I needed", "intent": "goodbye", "entities": {}},
    {"text": "Goodbye", "intent": "goodbye", "entities": {}},
    {"text": "See you later", "intent": "goodbye", "entities": {}},
    {"text": "Thanks, bye", "intent": "goodbye", "entities": {}},
    {"text": "That will be all", "intent": "goodbye", "entities": {}},
    {"text": "Thank you for your help", "intent": "goodbye", "entities": {}},
    {"text": "I'm done, thanks", "intent": "goodbye", "entities": {}},
    {"text": "Have a good day", "intent": "goodbye", "entities": {}},
    {"text": "Bye bye!", "intent": "goodbye", "entities": {}},
    {"text": "See ya", "intent": "goodbye", "entities": {}},
    {"text": "Thanks for the support, bye", "intent": "goodbye", "entities": {}},
    {"text": "Okay bye", "intent": "goodbye", "entities": {}},
    {"text": "I will go now", "intent": "goodbye", "entities": {}},
    {"text": "Talk to you later", "intent": "goodbye", "entities": {}},
    {"text": "Thanks a lot, goodbye", "intent": "goodbye", "entities": {}},
    {"text": "See you soon", "intent": "goodbye", "entities": {}},
    {"text": "All set, thanks, bye", "intent": "goodbye", "entities": {}},
    {"text": "Have a nice day", "intent": "goodbye", "entities": {}},
    {"text": "Have a great day", "intent": "goodbye", "entities": {}},
    {"text": "Bye friend", "intent": "goodbye", "entities": {}},
    {"text": "Thanks, I am logging off", "intent": "goodbye", "entities": {}},
    {"text": "No more questions, thanks", "intent": "goodbye", "entities": {}},
    {"text": "Goodbye support", "intent": "goodbye", "entities": {}},
    {"text": "Thanks for help, bye", "intent": "goodbye", "entities": {}},
    {"text": "Catch you later", "intent": "goodbye", "entities": {}},
    {"text": "Bye, have a good one", "intent": "goodbye", "entities": {}},
    {"text": "I'm off, goodbye", "intent": "goodbye", "entities": {}},
    {"text": "Thanks again, bye", "intent": "goodbye", "entities": {}},
]

# All possible intents
INTENTS = [
    "check_order_status",
    "cancel_order",
    "request_refund",
    "greeting",
    "goodbye"
]